run:
  timeout: 5m
  go: '1.22'
  skip-dirs-use-default: false
  tests: true

issues:
  max-same-issues: 0

  exclude:
    - G404 # Weak random number generator
    - SA9003 # Empty branch

  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - maintidx
        - bodyclose
        - goconst
        - forbidigo
        - contextcheck
    - linters:
        - depguard
      text: "is not allowed from list 'Main'"

linters-settings:
  gosec:
    excludes:
      - G204

  cyclop:
    max-complexity: 20

  gci:
    sections:
      - standard
      - default

  lll:
    line-length: 210

  nestif:
    min-complexity: 7

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: goCamel

  forbidigo:
    forbid:
      - .*\.Fatal.*

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - grouper
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - exportloopref
    - forbidigo
    #    - funlen
    #    - gci
    #    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    #    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    #    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    #    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
