version: "3.9"
volumes:
  pg-data:
services:
  pg-final:
    hostname: 'pg-final'
    container_name: 'pg-final'
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: final
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d final"]
      interval: 5s
      timeout: 5s
      retries: 5

  # redis-final:
  #   hostname: 'redis-final'
  #   container_name: 'redis-final'
  #   image: redis:7.2.4-alpine
  #   ports:
  #     - 6381:6379

  mongo-final:
    hostname: 'mongo-final'
    container_name: 'mongo-final'
    image: mongo:6-jammy
    ports:
      - 27018:27017

  rabbitmq-final:
    hostname: 'rabbitmq-final'
    container_name: 'rabbitmq-final'
    image: 'rabbitmq:3.13-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

  # proxy:
  #   image: nginx:1.23.4
  #   container_name: 'proxy'
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   command: [nginx-debug, '-g', 'daemon off;']
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - friends1
  #     - friends2
